---
  -
    clean: ["~"]
  -
    link: 
      "~/.dotfiles": ""
      "~/.bash_it": "../submodules/bash-it"
      #"~/.bashrc": "../homedir/bashrc"
      "~/.bash_profile": "../homedir/bash_profile"
      "~/bin": "../bin"
      "~/.bundle": "../.bundle"
      "~/.profile": "../homedir/profile"
      "~/.vimrc": "../homedir/vimrc"
      "~/.zshrc": "../homedir/zshrc"
  -
    shell: [
      ["git submodule update --init --recursive --remote", "Install/updating submodules"]
      ["~/.bash_it/install.sh", "Install/updating submodules"]
    ]
#
