---
  -
    clean: ["~"]
  -
    link: 
      "~/.dotfiles":
        path: ".."
        force: true
      "~/.bash_it":
        path: "../submodules/bash_it"
        force: true
      #"~/.bashrc": "../homedir/bashrc"
      "~/.bash_profile":
        path: "../homedir/bash_profile"
        force: true
      "~/bin":
        path: "../bin"
        force: true
      "~/.jekyllconfig":
        path: "../homedir/jekyllconfig"
        force: true
      "~/.bash_it/themes/phathocker":
        path: "../themes/phathocker"
        force: true
      "~/.vim":
        create: true
        path: "~/.vim"
      "~/.vimrc":
        path: "../homedir/vimrc"
        force: true
      "~/.zshrc":
        path: "../homedir/zshrc"
        force: true
  -
    shell: [
      ["../script/bashit >> /tmp/bashit.install", "Install/Configure Bash It"],
      ["../script/oh-my-zsh >> /tmp/oh-my-zsh.install", "Install/Configure Oh-My-ZSH"],
      ["git submodule update --init --recursive --remote", "Install/updating submodules"],
      ["../script/vundle >> /tmp/vundle.install", "Install/Configure Vundle"],
      ["../script/ruby >> /tmp/ruby.install", "Install/Configure Ruby"],
      ["../script/puppet >> /tmp/puppet.install", "Install/Configure Puppet"]
    ]
