#!/bin/bash

orig_dir=$(pwd)
script_dir=${orig_dir}/script
debug=false

if [ "$debug" == true ]; then
	BASH='bash -x'
else
	BASH='bash'
fi

cd $script_dir
$BASH ./update
$BASH ./yum
$BASH ./dotbot
#$BASH ./ruby
$BASH ./bashit
$BASH ./oh-my-zsh
$BASH ./vundle
#$BASH ./puppet

cd $orig_dir
