#!/bin/bash

if [ ! -d ../submodules/oh-my-zsh ]; then
  git submodule add git://github.com/robbyrussell/oh-my-zsh.git ../submodules/oh-my-zsh
fi

cd ../submodulest submodule update
git submodule update --recursive
