#!/bin/bash
readonly ORIG_DIR=`dirname $0`
readonly QUIET="> /dev/null 2>&1"

# Put us where we belong, in the root dir of the repo
function go_to_repo_root () {
  local DIR=`dirname $0`
	if [[ `pwd | awk -F/ '{print $NF}'` == 'script' ]]; then
    cd ${DIR}/../
	fi
  pwd
}

# Git functions
function check_git() {
  which git > /dev/null
  return $?
}

function is_git_repo() {
  local result=""
  [ -d .git ] && result=true || result=false
  return $result
}

function is_clean() {
  local result=""
  local porcelain=`git status --porcelain`
  # Pending git commit?
  if [ ! -z "$porcelain" ]; then
    echo "Has a dirty tree, won't auto-update!"
    exit
  fi
}

function get_current_branch() {
  local current=`git symbolic-ref HEAD`
  if [ -z $current ]; then
    ref=`git log -1 --pretty=format:%h`
    echo "Not currently on any branch (ref: #{ref}), won't auto-update!"
    exit
  fi
  echo $current
}

function on_master_branch() {
  local current=$1
  local master="refs/heads/master"

  if [[ $current != $master ]]; then
    echo "On a non-master branch '$current', won't auto-update!"
    exit
  fi
}

function has_upstream_changes() {
  local upstream_changes=`git rev-list --count master..origin/master`
  if [ "$upstream_changes" -ne 0 ]; then
    echo "Upstream repo has changes, won't auto-update!"
    exit
  fi
}

function is_fast_forwardable() {
  local fast_forwardable=`git rev-list --count origin/master..master`
  if [ "$fast_forwardable" -ne 0 ]; then
    echo "Master branch is out of sync, won't auto-update!"
    exit
  fi
}

function git_reset() {
  git reset --hard origin/master $QUIET
  if [ $? -ne 0 ]; then
    echo "Git reset failed, won't auto-update!"
    exit
  fi
}

function git_clean() {
  git clean -qdf
  if [ $? -ne 0 ]; then
    echo "Git clean failed, won't auto-update!"
    exit
  fi
}

function auto_update_repo() {
  if [[ check_git -eq 0 ]] && [[ is_git_repo == 'true' ]]; then
    git fetch -q origin
  fi

  #is_clean
  local current_branch=`get_current_branch`
  on_master_branch $current_branch
  has_upstream_changes
  is_fast_forwardable
}

function submodule_update() {
  cd submodules
	git submodule update --init --recursive --remote
	go_to_repo_root
}

function main() {
  go_to_repo_root
	submodule_update
  auto_update_repo
}

main
