#!/bin/bash

echo "Loading homedir/aliases"

if [ -f ~/.dotfiles/private/aliases ]; then
  source ~/.dotfiles/private/aliases
fi
export VAGRANT_DOTFILE_PATH=/tmp/
export TMPDIR=/tmp/

eval `keychain --eval --agents ssh id_dsa`

# Auto-sudo
alias ps="sudo ps"
alias yum="sudo yum"
alias tail="sudo tail"
alias netstat="sudo netstat -pantu"
alias npmg="sudo -E npm install -g"

# Bash
alias sb="reload"
alias b="vim ~/.dotfiles/homedir/aliases"
alias bp="vim ~/.bash_profile"
alias v="vim ~/.vimrc"

# Bash-it
alias bha='bash-it help aliases'
alias bhc='bash-it help completions'
alias bhp='bash-it help plugins'

# Grep
export GREP_COLOR='1;31'
export CLICOLOR=1
alias grep='egrep -i'

# Git
eval "$(hub alias -s)"
alias ga='git add --all'
alias gcb='git checkout -b'
alias gct='git checkout -t origin/'
alias gdc='git diff --cached'
alias gfsck='git fsck'
alias ggc='git gc'
alias gpush="git push -u origin"
alias gpull="git pull"
alias gshow='git remote show origin'
alias gsl='git stash list'
alias gt='git tree'
alias gu='git up'
function ua() {
for list in `ls`; do
  if [ -d $list ]; then
    cd $list
    gpull
    cd ..
  fi
done
}

# Locations
alias dot='cd ~/.dotfiles/'

# SSH
SSH_ARGS="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ConnectTimeout=1 -o ConnectionAttempts=1"
alias sshpass="/usr/bin/ssh -l root -X ${SSH_ARGS} -o PubkeyAuthentication=no"
alias ssh="/usr/bin/ssh -l root -X ${SSH_ARGS}"
alias scp="/usr/bin/scp ${SSH_ARGS}"

# Misc
alias llh="ls -lha"
alias cdu='du -ms * | sort -n'
alias pl='puppet-lint *'

# Ruby
function gunit() {
  bundle install
  bundle update
  bundle exec guard
}
